project:
  type: website

website:
  title: "isss608-jan2526"
  navbar:
    right: 
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
    left:
      - text: Hands-on Exercise
        menu: 
          - href: Hands-on_Ex/Hands-on_ex01/handson_ex1.html
            text: Hands-on Exercise 1  
          - href: Hands-on_Ex/Hands-on_ex02/handson_ex2.html
            text: Hands-on Exercise 2 
          - href: Hands-on_Ex/Hands-on_ex03/handson_ex3.html
            text: Hands-on Exercise 3
          - href: Hands-on_Ex/Hands-on_ex03/handson_ex3b.html
            text: Hands-on Exercise 3b
          - href: Hands-on_Ex/Hands-on_ex04/handson_ex4.html
            text: Hands-on Exercise 4
          - href: Hands-on_Ex/Hands-on_ex04/handson_ex4b.html
            text: Hands-on Exercise 4b
          - href: Hands-on_Ex/Hands-on_ex04/handson_ex4c.html
            text: Hands-on Exercise 4c
          - href: Hands-on_Ex/Hands-on_ex04/handson_ex4d.html
            text: Hands-on Exercise 4d
          - href: Hands-on_Ex/Hands-on_ex05/handson_ex5.html
            text: Hands-on Exercise 5
          - href: Hands-on_Ex/Hands-on_ex05/handson_ex5b.html
            text: Hands-on Exercise 5b
          - href: Hands-on_Ex/Hands-on_ex05/handson_ex5c.html
            text: Hands-on Exercise 5c
          - href: Hands-on_Ex/Hands-on_ex05/handson_ex5d.html
            text: Hands-on Exercise 5d
          - href: Hands-on_Ex/Hands-on_ex05/handson_ex5e.html
            text: Hands-on Exercise 5e
          - href: Hands-on_Ex/Hands-on_ex06/handson_ex6.html
            text: Hands-on Exercise 6
      - text: In-class Exercise
        menu: 
          - href: Inclass_Ex/Inclass_ex01/inclass_ex1.html
            text: In-class Exercise 1
          - href: Inclass_Ex/Inclass_ex02/inclass_ex2.html
            text: In-class Exercise 2
          - href: Inclass_Ex/Inclass_ex03/inclass_ex3.html
            text: In-class Exercise 3
          - href: Inclass_Ex/Inclass_ex04/inclass_ex4.html
            text: In-class Exercise 4
      - text: Take-home Exercise
        menu: 
          - href: takehome_ex/takehome1/takehome_ex1.html
            text: Take-home Exercise 1

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

